const canvas = document.getElementById("gameCanvas");
const ctx = canvas.getContext("2d");

canvas.width = window.innerWidth;
canvas.height = window.innerHeight;

let cash = 0;
let wantedStars = "⭐☆☆☆☆";
let currentMissionState = "START";

let player = { x: canvas.width / 2, y: canvas.height / 2, size: 25, speed: 4, color: "#FFCC00" };

let roads = [
    { x: 0, y: canvas.height / 2 - 40, width: canvas.width, height: 80 }, 
        { x: canvas.width / 3 - 40, y: 0, width: 80, height: canvas.height }  
        ];

        let buildings = [
            { name: "Oshodi Danfo Park", x: 40, y: 40, width: 140, height: 100, color: "#37474f" },
                { name: "LASTMA Roadblock", x: canvas.width - 160, y: canvas.height / 2 - 35, width: 30, height: 70, color: "#d84315" },
                    { name: "Local Mama Put Shop", x: canvas.width / 2 + 20, y: canvas.height - 150, width: 120, height: 90, color: "#8d6e63" }
                    ];

                    let traffic = [
                        { x: 0, y: canvas.height / 2 - 25, size: 20, speed: 2, color: "#FFA500", label: "Keke" },
                            { x: canvas.width / 2, y: canvas.height / 2 + 10, size: 25, speed: -3, color: "#FFCC00", label: "Danfo" },
                                { x: canvas.width, y: canvas.height / 2 - 20, size: 22, speed: -1.5, color: "#ffffff", label: "Car" }
                                ];

                                let moveUp = false, moveDown = false, moveLeft = false, moveRight = false;
                                let currentZone = "Lagos Mainland";

                                function draw() {
                                    ctx.fillStyle = "#2e7d32";
                                        ctx.fillRect(0, 0, canvas.width, canvas.height);

                                            ctx.fillStyle = "#424242";
                                                roads.forEach(road => {
                                                        ctx.fillRect(road.x, road.y, road.width, road.height);
                                                                ctx.strokeStyle = "#ffeb3b";
                                                                        ctx.lineWidth = 2;
                                                                                ctx.beginPath();
                                                                                        if (road.width > road.height) { 
                                                                                                    ctx.moveTo(road.x, road.y + road.height / 2);
                                                                                                                ctx.lineTo(road.x + road.width, road.y + road.height / 2);
                                                                                                                        } else { 
                                                                                                                                    ctx.moveTo(road.x + road.width / 2, road.y);
                                                                                                                                                ctx.lineTo(road.x + road.width / 2, road.y + road.height);
                                                                                                                                                        }
                                                                                                                                                                ctx.stroke();
                                                                                                                                                                    });

                                                                                                                                                                        buildings.forEach(bld => {
                                                                                                                                                                                ctx.fillStyle = bld.color;
                                                                                                                                                                                        ctx.fillRect(bld.x, bld.y, bld.width, bld.height);
                                                                                                                                                                                                ctx.fillStyle = "#ffffff";
                                                                                                                                                                                                        ctx.font = "12px sans-serif";
                                                                                                                                                                                                                ctx.textAlign = "center";
                                                                                                                                                                                                                        ctx.fillText(bld.name, bld.x + bld.width / 2, bld.y + bld.height / 2);
                                                                                                                                                                                                                            });

                                                                                                                                                                                                                                traffic.forEach(car => {
                                                                                                                                                                                                                                        ctx.fillStyle = car.color;
                                                                                                                                                                                                                                                ctx.fillRect(car.x, car.y, car.size * 1.3, car.size);
                                                                                                                                                                                                                                                        ctx.fillStyle = "#000";
                                                                                                                                                                                                                                                                ctx.font = "10px Arial";
                                                                                                                                                                                                                                                                        ctx.fillText(car.label, car.x + 5, car.y + car.size - 5);
                                                                                                                                                                                                                                                                            });

                                                                                                                                                                                                                                                                                ctx.fillStyle = player.color;
                                                                                                                                                                                                                                                                                    ctx.fillRect(player.x - player.size / 2, player.y - player.size / 2, player.size, player.size * 1.4);
                                                                                                                                                                                                                                                                                        ctx.fillStyle = "#000";
                                                                                                                                                                                                                                                                                            ctx.fillRect(player.x - player.size / 2, player.y - player.size / 5, player.size, 4);
                                                                                                                                                                                                                                                                                                ctx.fillRect(player.x - player.size / 2, player.y + player.size / 4, player.size, 4);
                                                                                                                                                                                                                                                                                                }

                                                                                                                                                                                                                                                                                                function checkMissionLogic() {
                                                                                                                                                                                                                                                                                                    if (currentZone === "Oshodi Danfo Park" && currentMissionState === "START") {
                                                                                                                                                                                                                                                                                                            document.getElementById("objective").innerText = "Passengers loaded! Take them to Local Mama Put Shop.";
                                                                                                                                                                                                                                                                                                                    currentMissionState = "HAS_PASSENGERS";
                                                                                                                                                                                                                                                                                                                        } 
                                                                                                                                                                                                                                                                                                                            else if (currentZone === "Local Mama Put Shop" && currentMissionState === "HAS_PASSENGERS") {
                                                                                                                                                                                                                                                                                                                                    cash += 2500;
                                                                                                                                                                                                                                                                                                                                            document.getElementById("cash").innerText = cash;
                                                                                                                                                                                                                                                                                                                                                    document.getElementById("objective").innerText = "Drop-off complete! Earned ₦2,500. Return to Oshodi Park.";
                                                                                                                                                                                                                                                                                                                                                            currentMissionState = "START";
                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                    else if (currentZone === "LASTMA Roadblock") {
                                                                                                                                                                                                                                                                                                                                                                            wantedStars = "⭐⭐⭐☆☆";
                                                                                                                                                                                                                                                                                                                                                                                    document.getElementById("wanted").innerText = wantedStars;
                                                                                                                                                                                                                                                                                                                                                                                            document.getElementById("objective").innerText = "LASTMA caught you dropping off illegally! Wanted Level Up!";
                                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                                                }

                                                                                                                                                                                                                                                                                                                                                                                                function update() {
                                                                                                                                                                                                                                                                                                                                                                                                    if (moveUp && player.y > 0) player.y -= player.speed;
                                                                                                                                                                                                                                                                                                                                                                                                        if (moveDown && player.y < canvas.height) player.y += player.speed;
                                                                                                                                                                                                                                                                                                                                                                                                            if (moveLeft && player.x > 0) player.x -= player.speed;
                                                                                                                                                                                                                                                                                                                                                                                                                if (moveRight && player.x < canvas.width) player.x += player.speed;

                                                                                                                                                                                                                                                                                                                                                                                                                    traffic.forEach(car => {
                                                                                                                                                                                                                                                                                                                                                                                                                            car.x += car.speed;
                                                                                                                                                                                                                                                                                                                                                                                                                                    if (car.speed > 0 && car.x > canvas.width) car.x = -40;
                                                                                                                                                                                                                                                                                                                                                                                                                                            if (car.speed < 0 && car.x < -40) car.x = canvas.width;
                                                                                                                                                                                                                                                                                                                                                                                                                                                });

                                                                                                                                                                                                                                                                                                                                                                                                                                                    currentZone = "Lagos Streets";
                                                                                                                                                                                                                                                                                                                                                                                                                                                        buildings.forEach(bld => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                if (player.x > bld.x && player.x < bld.x + bld.width &&
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            player.y > bld.y && player.y < bld.y + bld.height) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        currentZone = bld.name;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        document.getElementById("zone").innerText = currentZone;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                checkMissionLogic();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                function gameLoop() {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    update();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        draw();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            requestAnimationFrame(gameLoop);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            function setupTouchBtn(id, pressCallback, releaseCallback) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                const btn = document.getElementById(id);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    btn.addEventListener("touchstart", (e) => { e.preventDefault(); pressCallback(); });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        btn.addEventListener("touchend", (e) => { e.preventDefault(); releaseCallback(); });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        setupTouchBtn("btn-up", () => moveUp = true, () => moveUp = false);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        setupTouchBtn("btn-down", () => moveDown = true, () => moveDown = false);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        setupTouchBtn("btn-left", () => moveLeft = true, () => moveLeft = false);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        setupTouchBtn("btn-right", () => moveRight = true, () => moveRight = false);

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        gameLoop();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        